import { useState, useEffect } from 'react';

const useLanguage = () => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('selectedLanguage') || 'en';
  });

  useEffect(() => {
    // Listen for storage changes from other tabs/windows
    const handleStorageChange = (e) => {
      if (e.key === 'selectedLanguage' && e.newValue) {
        setCurrentLanguage(e.newValue);
      }
    };
    
    // Listen for custom language change event
    const handleLanguageChange = (e) => {
      setCurrentLanguage(e.detail);
    };
    
    window.addEventListener('storage', handleStorageChange);
    window.addEventListener('languageChange', handleLanguageChange);
    
    return () => {
      window.removeEventListener('storage', handleStorageChange);
      window.removeEventListener('languageChange', handleLanguageChange);
    };
  }, []);

  const languages = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
    { code: 'zh', name: '中文', flag: '🇨🇳' },
    { code: 'it', name: 'Italiano', flag: '🇮🇹' },
    { code: 'ja', name: '日本語', flag: '🇯🇵' }
  ];

  const translations = {
    en: {
      // Navigation
      profile: 'Profile',
      projects: 'Projects',
      mysteryProject: 'Mystery Project',
      contact: 'Contact',
      settings: 'Settings',

      // Projects Page
      projectsTitle: 'My Projects',
      projectsSubtitle: 'A showcase of my technical expertise and creativity',
      liveDemo: 'Live Demo',
      repository: 'Repository',
      ecommerceTitle: 'E-Commerce Platform',
      ecommerceDesc: 'A full-stack e-commerce solution built with React and Node.js, featuring user authentication, payment integration, and admin dashboard.',
      ecommerceSuggestion: 'Great project! Consider adding real-time notifications for order updates.',
      analyticsTitle: 'Data Analytics Dashboard',
      analyticsDesc: 'Interactive dashboard for data visualization and analytics using Python and React, with real-time data processing capabilities.',
      analyticsSuggestion: 'Impressive visualization! Adding export functionality would be valuable.',
      taskTitle: 'Task Management App',
      taskDesc: 'A collaborative task management application with real-time updates, team collaboration features, and progress tracking.',
      taskSuggestion: 'Love the real-time features! Mobile app version would be amazing.',
      weatherTitle: 'Weather Forecast App',
      weatherDesc: 'Modern weather application with location-based forecasts, interactive maps, and weather alerts using multiple APIs.',
      weatherSuggestion: 'Beautiful UI! Adding weather history charts would be a nice touch.',
      mlTitle: 'Machine Learning Model',
      mlDesc: 'Predictive analytics model for customer behavior analysis using Python and scikit-learn with web interface.',
      mlSuggestion: 'Excellent model accuracy! Consider adding model explanation features.',
      socialTitle: 'Social Media Clone',
      socialDesc: 'Full-featured social media platform with posts, comments, likes, real-time messaging, and user profiles.',
      socialSuggestion: 'Great social features! Adding story functionality would be trendy.',

      // Current Project Page
      mysteryProjectTitle: 'Mystery Project: AI-Powered Maps Assistant',
      mysteryProjectSubtitle: 'An intelligent journey locator companion that understands context and provides smart suggestions',
      projectAim: 'Project Aim',
      projectAimDescription: 'To develop an AI-powered maps assistant that can understand journey context, provide intelligent suggestions, detect potential issues, and help users navigate better and faster. The system will integrate with popular mapping platforms and support multiple navigation scenarios.',
      realtimeAnalysis: 'Real-time maps analysis and suggestions',
      contextAwareCompletion: 'Context-aware auto-completion',
      bugDetection: 'Bug detection and prevention',
      codeOptimization: 'Route optimization recommendations',
      multiLanguageSupport: 'Multi-language support (English, Spanish, French, etc.)',
      wantToContribute: 'Want to Contribute?',
      contributeDescription: 'This project is looking for passionate developers, AI enthusiasts, and beta testers to help make this vision a reality. Whether you\'re interested in machine learning, IDE development, or user experience design, there\'s a place for you!',
      joinProject: 'Join the Project',
      joinMysteryProject: 'Join the Mystery Project',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      yourSkills: 'Your Skills',
      skillsPlaceholder: 'e.g., Python, Machine Learning, React',
      whyInterested: 'Why are you interested?',
      sendApplication: 'Send Application',
      thankYouMessage: 'Thank you for your interest! I will get back to you soon.',
      
      // Current Issues and Limitations
      currentDrawbacks: 'Current Drawbacks',
      highComputationalReq: 'High computational requirements for real-time processing',
      accuracyVaries: 'Accuracy varies significantly across different programming languages',
      contextLimited: 'Context understanding limited to current file scope',
      integrationChallenges: 'Integration challenges with various IDE platforms',
      
      technicalLimitations: 'Technical Limitations',
      modelSizeConstraints: 'Model size constraints for local deployment',
      limitedTrainingData: 'Limited training data for niche programming domains',
      complexArchitecture: 'Difficulty in understanding complex project architectures',
      performanceBottlenecks: 'Performance bottlenecks with large codebases',
      crossPlatformIssues: 'Cross-platform compatibility issues',
      
      currentIssues: 'Current Issues',
      memoryLeaks: 'Memory leaks in the background processing service',
      inconsistentSuggestions: 'Inconsistent suggestion quality for edge cases',
      extensionCrashes: 'IDE extension crashes with certain file types',
      slowResponseTimes: 'Slow response times for complex code analysis',
      authenticationIssues: 'Authentication issues with cloud-based features',
      
      developmentPhase: 'Development Phase',
      phaseText: 'Phase 3 of 5 - Beta Testing & Optimization',
      phaseDescription: 'Currently in the beta testing phase where we\'re gathering user feedback, optimizing performance, and fixing critical bugs. The core AI model is functional, and we\'re now focusing on improving accuracy and user experience.',
      phaseResearchPlanning: 'Phase 1: Research & Planning',
      phaseCoreDevlopment: 'Phase 2: Core Development',
      phaseBetaTesting: 'Phase 3: Beta Testing',
      phaseProductionRelease: 'Phase 4: Production Release',
      phaseFeatureEnhancement: 'Phase 5: Feature Enhancement',

      // Profile Page
      welcomeHey: 'Hey,',
      welcomeTitle: 'Welcome',
      welcomeTo: 'to my portfolio',
      welcomeName: "I'm Sahil Shrivastav",
      profileSubtitle: 'Software Engineer | Data Analyst | Developer',
      profileDescription: "I'm a passionate software engineer and data analyst with a keen interest in learning new technologies. Always working on exciting projects and exploring innovative solutions.",
      aboutMe: 'About Me',
      aboutMeText: "I'm a passionate software engineer and data analyst with a keen interest in learning new technologies. I'm always working on exciting projects and exploring innovative solutions to complex problems.",
      downloadCV: 'Download CV',
      technicalSkills: 'Technical Skills',
      myMindset: 'My Mindset',
      alwaysLearning: 'Always Learning',
      alwaysLearningText: 'Keen to learn new things and stay updated with latest technologies',
      innovationFocused: 'Innovation Focused',
      innovationFocusedText: 'Always into new tech and exploring cutting-edge solutions',
      projectDriven: 'Project Driven',
      projectDrivenText: 'Anytime always working on new things and exciting projects',
      myProjects: 'My Projects',
      myProjectsText: 'Explore my collection of innovative projects and applications',
      viewProjects: 'View Projects',
      currentMysteryProject: 'Current Mystery Project',
      currentMysteryProjectText: 'Discover my ongoing project and contribute to its development',
      learnMore: 'Learn More',
      getInTouch: 'Get In Touch',
      getInTouchText: 'Have a question or want to collaborate? Let\'s connect!',
      contactMe: 'Contact Me',
      
      // Contact Page
      contactTitle: 'Get In Touch',
      contactSubtitle: 'Have a question, want to collaborate, or just say hello? I\'d love to hear from you!',
      emailMe: 'Email Me',
      emailMeDesc: 'I\'ll get back to you within 24 hours',
      sendEmail: 'Send Email',
      letsDiscuss: 'Let\'s Discuss',
      letsDiscussDesc: 'Open to new opportunities and collaborations',
      availableFor: 'Available For',
      availableForDesc: 'Freelance projects, full-time roles, and consulting',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Your full name',
      emailAddress: 'Email Address',
      emailPlaceholder: 'your.email@example.com',
      subject: 'Subject',
      subjectPlaceholder: 'What\'s this about?',
      messageLabel: 'Message',
      messagePlaceholder: 'Tell me about your project, question, or just say hello...',
      sendMessage: 'Send Message',
      sending: 'Sending...',
      messageSentSuccess: 'Thank you! Your message has been sent successfully.',

      // Settings
      settingsTitle: 'Settings',
      settingsSubtitle: 'Customize your portfolio experience',
      themeSettings: 'Theme Settings',
      autoChange: 'Auto Change',
      autoChangeDesc: 'Automatically cycle through color themes',
      blueTheme: 'Blue Theme',
      blueThemeDesc: 'A cool and professional blue color scheme',
      redTheme: 'Red Theme',
      redThemeDesc: 'A vibrant and energetic red color scheme',
      greyTheme: 'Grey Theme',
      greyThemeDesc: 'A minimal and elegant grey color scheme',
      languageSettings: 'Language Settings',
      selectLanguage: 'Select Language',
      bugReport: 'Report Bug',
      bugReportDesc: 'Help us improve by reporting issues',
      bugScreenshot: 'Bug Screenshot',
      bugDetails: 'Bug Details',
      bugDetailsPlaceholder: 'Describe the bug you encountered...',
      submitBugReport: 'Submit Bug Report',
      bugReportSuccess: 'Bug report submitted successfully!',

      // Common
      save: 'Save',
      cancel: 'Cancel',
      submit: 'Submit',
      close: 'Close'
    },
    es: {
      // Navigation
      profile: 'Perfil',
      projects: 'Proyectos',
      mysteryProject: 'Proyecto Misterioso',
      contact: 'Contacto',
      settings: 'Configuración',

      // Projects Page
      projectsTitle: 'Mis Proyectos',
      projectsSubtitle: 'Una muestra de mi experiencia técnica y creatividad',
      liveDemo: 'Demo en Vivo',
      repository: 'Repositorio',
      ecommerceTitle: 'Plataforma de Comercio Electrónico',
      ecommerceDesc: 'Una solución completa de comercio electrónico construida con React y Node.js, con autenticación de usuarios, integración de pagos y panel de administración.',
      ecommerceSuggestion: '¡Gran proyecto! Considera agregar notificaciones en tiempo real para actualizaciones de pedidos.',
      analyticsTitle: 'Panel de Análisis de Datos',
      analyticsDesc: 'Panel interactivo para visualización y análisis de datos usando Python y React, con capacidades de procesamiento de datos en tiempo real.',
      analyticsSuggestion: '¡Visualización impresionante! Agregar funcionalidad de exportación sería valioso.',
      taskTitle: 'Aplicación de Gestión de Tareas',
      taskDesc: 'Una aplicación colaborativa de gestión de tareas con actualizaciones en tiempo real, características de colaboración en equipo y seguimiento de progreso.',
      taskSuggestion: '¡Me encantan las características en tiempo real! Una versión de aplicación móvil sería increíble.',
      weatherTitle: 'Aplicación de Pronóstico del Tiempo',
      weatherDesc: 'Aplicación moderna del clima con pronósticos basados en ubicación, mapas interactivos y alertas meteorológicas usando múltiples APIs.',
      weatherSuggestion: '¡Hermosa interfaz! Agregar gráficos de historial del clima sería un buen toque.',
      mlTitle: 'Modelo de Aprendizaje Automático',
      mlDesc: 'Modelo de análisis predictivo para análisis de comportamiento del cliente usando Python y scikit-learn con interfaz web.',
      mlSuggestion: '¡Excelente precisión del modelo! Considera agregar características de explicación del modelo.',
      socialTitle: 'Clon de Redes Sociales',
      socialDesc: 'Plataforma de redes sociales con todas las características: publicaciones, comentarios, likes, mensajería en tiempo real y perfiles de usuario.',
      socialSuggestion: '¡Grandes características sociales! Agregar funcionalidad de historias estaría de moda.',

      // Current Project Page
      mysteryProjectTitle: 'Proyecto Misterioso: Asistente de Código con IA',
      mysteryProjectSubtitle: 'Un compañero de programación inteligente que entiende el contexto y proporciona sugerencias inteligentes',
      projectAim: 'Objetivo del Proyecto',
      projectAimDescription: 'Desarrollar un asistente de código impulsado por IA que pueda entender el contexto del código, proporcionar sugerencias inteligentes, detectar errores potenciales y ayudar a los desarrolladores a escribir mejor código más rápido. El sistema se integrará con IDEs populares y soportará múltiples lenguajes de programación.',
      realtimeAnalysis: 'Análisis de código en tiempo real y sugerencias',
      contextAwareCompletion: 'Autocompletado consciente del contexto',
      bugDetection: 'Detección y prevención de errores',
      codeOptimization: 'Recomendaciones de optimización de código',
      multiLanguageSupport: 'Soporte multi-idioma (Python, JavaScript, Java, etc.)',
      wantToContribute: '¿Quieres Contribuir?',
      contributeDescription: 'Este proyecto está buscando desarrolladores apasionados, entusiastas de IA y probadores beta para ayudar a hacer realidad esta visión. Ya sea que estés interesado en aprendizaje automático, desarrollo de IDE o diseño de experiencia de usuario, ¡hay un lugar para ti!',
      joinProject: 'Únete al Proyecto',
      joinMysteryProject: 'Únete al Proyecto Misterioso',
      fullName: 'Nombre Completo',
      emailAddress: 'Dirección de Email',
      yourSkills: 'Tus Habilidades',
      skillsPlaceholder: 'ej., Python, Machine Learning, React',
      whyInterested: '¿Por qué estás interesado?',
      sendApplication: 'Enviar Solicitud',
      thankYouMessage: '¡Gracias por tu interés! Te contactaré pronto.',
      
      // Current Issues and Limitations
      currentDrawbacks: 'Inconvenientes Actuales',
      highComputationalReq: 'Altos requisitos computacionales para procesamiento en tiempo real',
      accuracyVaries: 'La precisión varía significativamente entre diferentes lenguajes de programación',
      contextLimited: 'Comprensión del contexto limitada al alcance del archivo actual',
      integrationChallenges: 'Desafíos de integración con varias plataformas IDE',
      
      technicalLimitations: 'Limitaciones Técnicas',
      modelSizeConstraints: 'Restricciones de tamaño del modelo para implementación local',
      limitedTrainingData: 'Datos de entrenamiento limitados para dominios de programación especializados',
      complexArchitecture: 'Dificultad para entender arquitecturas de proyectos complejas',
      performanceBottlenecks: 'Cuellos de botella de rendimiento con bases de código grandes',
      crossPlatformIssues: 'Problemas de compatibilidad multiplataforma',
      
      currentIssues: 'Problemas Actuales',
      memoryLeaks: 'Fugas de memoria en el servicio de procesamiento en segundo plano',
      inconsistentSuggestions: 'Calidad inconsistente de sugerencias para casos extremos',
      extensionCrashes: 'Fallos de extensión IDE con ciertos tipos de archivo',
      slowResponseTimes: 'Tiempos de respuesta lentos para análisis de código complejo',
      authenticationIssues: 'Problemas de autenticación con características basadas en la nube',
      
      developmentPhase: 'Fase de Desarrollo',
      phaseText: 'Fase 3 de 5 - Pruebas Beta y Optimización',
      phaseDescription: 'Actualmente en la fase de pruebas beta donde estamos recopilando comentarios de usuarios, optimizando el rendimiento y corrigiendo errores críticos. El modelo de IA principal es funcional, y ahora nos estamos enfocando en mejorar la precisión y la experiencia del usuario.',
      phaseResearchPlanning: 'Fase 1: Investigación y Planificación',
      phaseCoreDevlopment: 'Fase 2: Desarrollo Principal',
      phaseBetaTesting: 'Fase 3: Pruebas Beta',
      phaseProductionRelease: 'Fase 4: Lanzamiento de Producción',
      phaseFeatureEnhancement: 'Fase 5: Mejora de Características',

      // Profile Page
      welcomeHey: 'Hola,',
      welcomeTitle: 'Bienvenido',
      welcomeTo: 'a mi portafolio',
      welcomeName: 'Soy Sahil Shrivastav',
      profileSubtitle: 'Ingeniero de Software | Analista de Datos | Desarrollador',
      profileDescription: 'Soy un ingeniero de software apasionado y analista de datos con un gran interés en aprender nuevas tecnologías. Siempre trabajando en proyectos emocionantes y explorando soluciones innovadoras.',
      aboutMe: 'Sobre Mí',
      aboutMeText: 'Soy un ingeniero de software apasionado y analista de datos con un gran interés en aprender nuevas tecnologías. Siempre estoy trabajando en proyectos emocionantes y explorando soluciones innovadoras a problemas complejos.',
      downloadCV: 'Descargar CV',
      technicalSkills: 'Habilidades Técnicas',
      myMindset: 'Mi Mentalidad',
      alwaysLearning: 'Siempre Aprendiendo',
      alwaysLearningText: 'Interesado en aprender cosas nuevas y mantenerse actualizado con las últimas tecnologías',
      innovationFocused: 'Enfocado en la Innovación',
      innovationFocusedText: 'Siempre en nuevas tecnologías y explorando soluciones de vanguardia',
      projectDriven: 'Impulsado por Proyectos',
      projectDrivenText: 'Siempre trabajando en cosas nuevas y proyectos emocionantes',
      myProjects: 'Mis Proyectos',
      myProjectsText: 'Explora mi colección de proyectos y aplicaciones innovadoras',
      viewProjects: 'Ver Proyectos',
      currentMysteryProject: 'Proyecto Misterioso Actual',
      currentMysteryProjectText: 'Descubre mi proyecto en curso y contribuye a su desarrollo',
      learnMore: 'Aprender Más',
      getInTouch: 'Ponerse en Contacto',
      getInTouchText: '¿Tienes una pregunta o quieres colaborar? ¡Conectémonos!',
      contactMe: 'Contáctame',
      
      // Contact Page
      contactTitle: 'Ponerse en Contacto',
      contactSubtitle: '¿Tienes una pregunta, quieres colaborar o simplemente saludar? ¡Me encantaría saber de ti!',
      emailMe: 'Envíame un Email',
      emailMeDesc: 'Te responderé en 24 horas',
      sendEmail: 'Enviar Email',
      letsDiscuss: 'Hablemos',
      letsDiscussDesc: 'Abierto a nuevas oportunidades y colaboraciones',
      availableFor: 'Disponible Para',
      availableForDesc: 'Proyectos freelance, roles de tiempo completo y consultoría',
      fullName: 'Nombre Completo',
      fullNamePlaceholder: 'Tu nombre completo',
      emailAddress: 'Dirección de Email',
      emailPlaceholder: 'tu.email@ejemplo.com',
      subject: 'Asunto',
      subjectPlaceholder: '¿De qué se trata?',
      messageLabel: 'Mensaje',
      messagePlaceholder: 'Cuéntame sobre tu proyecto, pregunta o simplemente saluda...',
      sendMessage: 'Enviar Mensaje',
      sending: 'Enviando...',
      messageSentSuccess: '¡Gracias! Tu mensaje ha sido enviado exitosamente.',

      // Settings
      settingsTitle: 'Configuración',
      settingsSubtitle: 'Personaliza tu experiencia del portafolio',
      themeSettings: 'Configuración de Tema',
      autoChange: 'Cambio Automático',
      autoChangeDesc: 'Cambiar automáticamente entre temas de color',
      blueTheme: 'Tema Azul',
      blueThemeDesc: 'Un esquema de colores azul fresco y profesional',
      redTheme: 'Tema Rojo',
      redThemeDesc: 'Un esquema de colores rojo vibrante y enérgico',
      greyTheme: 'Tema Gris',
      greyThemeDesc: 'Un esquema de colores gris minimalista y elegante',
      languageSettings: 'Configuración de Idioma',
      selectLanguage: 'Seleccionar Idioma',
      bugReport: 'Reportar Error',
      bugReportDesc: 'Ayúdanos a mejorar reportando problemas',
      bugScreenshot: 'Captura de Error',
      bugDetails: 'Detalles del Error',
      bugDetailsPlaceholder: 'Describe el error que encontraste...',
      submitBugReport: 'Enviar Reporte de Error',
      bugReportSuccess: '¡Reporte de error enviado exitosamente!',

      // Common
      save: 'Guardar',
      cancel: 'Cancelar',
      submit: 'Enviar',
      close: 'Cerrar'
    },
    fr: {
      // Navigation
      profile: 'Profil',
      projects: 'Projets',
      mysteryProject: 'Projet Mystère',
      contact: 'Contact',
      settings: 'Paramètres',

      // Projects Page
      projectsTitle: 'Mes Projets',
      projectsSubtitle: 'Une vitrine de mon expertise technique et de ma créativité',
      liveDemo: 'Démo en Direct',
      repository: 'Dépôt',
      ecommerceTitle: 'Plateforme E-Commerce',
      ecommerceDesc: 'Une solution e-commerce complète construite avec React et Node.js, comprenant l\'authentification des utilisateurs, l\'intégration de paiement et un tableau de bord administrateur.',
      ecommerceSuggestion: 'Excellent projet ! Considérez ajouter des notifications en temps réel pour les mises à jour de commandes.',
      analyticsTitle: 'Tableau de Bord d\'Analyse de Données',
      analyticsDesc: 'Tableau de bord interactif pour la visualisation et l\'analyse de données utilisant Python et React, avec des capacités de traitement de données en temps réel.',
      analyticsSuggestion: 'Visualisation impressionnante ! Ajouter une fonctionnalité d\'export serait précieux.',
      taskTitle: 'Application de Gestion de Tâches',
      taskDesc: 'Une application de gestion de tâches collaborative avec mises à jour en temps réel, fonctionnalités de collaboration d\'équipe et suivi de progression.',
      taskSuggestion: 'J\'adore les fonctionnalités temps réel ! Une version application mobile serait géniale.',
      weatherTitle: 'Application de Prévisions Météo',
      weatherDesc: 'Application météo moderne avec prévisions basées sur la localisation, cartes interactives et alertes météo utilisant plusieurs APIs.',
      weatherSuggestion: 'Belle interface ! Ajouter des graphiques d\'historique météo serait une belle touche.',
      mlTitle: 'Modèle d\'Apprentissage Automatique',
      mlDesc: 'Modèle d\'analyse prédictive pour l\'analyse du comportement client utilisant Python et scikit-learn avec interface web.',
      mlSuggestion: 'Excellente précision du modèle ! Considérez ajouter des fonctionnalités d\'explication du modèle.',
      socialTitle: 'Clone de Médias Sociaux',
      socialDesc: 'Plateforme de médias sociaux complète avec publications, commentaires, likes, messagerie en temps réel et profils utilisateur.',
      socialSuggestion: 'Excellentes fonctionnalités sociales ! Ajouter une fonctionnalité stories serait tendance.',

      // Current Project Page
      mysteryProjectTitle: 'Projet Mystère : Assistant de Code IA',
      mysteryProjectSubtitle: 'Un compagnon de codage intelligent qui comprend le contexte et fournit des suggestions intelligentes',
      projectAim: 'Objectif du Projet',
      projectAimDescription: 'Développer un assistant de code alimenté par IA qui peut comprendre le contexte du code, fournir des suggestions intelligentes, détecter les bugs potentiels et aider les développeurs à écrire un meilleur code plus rapidement. Le système s\'intégrera avec les IDEs populaires et supportera plusieurs langages de programmation.',
      realtimeAnalysis: 'Analyse de code en temps réel et suggestions',
      contextAwareCompletion: 'Auto-complétion consciente du contexte',
      bugDetection: 'Détection et prévention des bugs',
      codeOptimization: 'Recommandations d\'optimisation de code',
      multiLanguageSupport: 'Support multi-langage (Python, JavaScript, Java, etc.)',
      wantToContribute: 'Voulez-vous Contribuer ?',
      contributeDescription: 'Ce projet recherche des développeurs passionnés, des passionnés d\'IA et des testeurs bêta pour aider à réaliser cette vision. Que vous soyez intéressé par l\'apprentissage automatique, le développement d\'IDE ou la conception d\'expérience utilisateur, il y a une place pour vous !',
      joinProject: 'Rejoindre le Projet',
      joinMysteryProject: 'Rejoindre le Projet Mystère',
      fullName: 'Nom Complet',
      emailAddress: 'Adresse Email',
      yourSkills: 'Vos Compétences',
      skillsPlaceholder: 'ex., Python, Machine Learning, React',
      whyInterested: 'Pourquoi êtes-vous intéressé ?',
      sendApplication: 'Envoyer la Candidature',
      thankYouMessage: 'Merci pour votre intérêt ! Je vous recontacterai bientôt.',
      
      // Current Issues and Limitations
      currentDrawbacks: 'Inconvénients Actuels',
      highComputationalReq: 'Exigences computationnelles élevées pour le traitement en temps réel',
      accuracyVaries: 'La précision varie considérablement entre les différents langages de programmation',
      contextLimited: 'Compréhension du contexte limitée à la portée du fichier actuel',
      integrationChallenges: 'Défis d\'intégration avec diverses plateformes IDE',
      
      technicalLimitations: 'Limitations Techniques',
      modelSizeConstraints: 'Contraintes de taille de modèle pour le déploiement local',
      limitedTrainingData: 'Données d\'entraînement limitées pour les domaines de programmation de niche',
      complexArchitecture: 'Difficulté à comprendre les architectures de projet complexes',
      performanceBottlenecks: 'Goulots d\'étranglement de performance avec de grandes bases de code',
      crossPlatformIssues: 'Problèmes de compatibilité multiplateforme',
      
      currentIssues: 'Problèmes Actuels',
      memoryLeaks: 'Fuites de mémoire dans le service de traitement en arrière-plan',
      inconsistentSuggestions: 'Qualité de suggestion incohérente pour les cas limites',
      extensionCrashes: 'Plantages d\'extension IDE avec certains types de fichiers',
      slowResponseTimes: 'Temps de réponse lents pour l\'analyse de code complexe',
      authenticationIssues: 'Problèmes d\'authentification avec les fonctionnalités basées sur le cloud',
      
      developmentPhase: 'Phase de Développement',
      phaseText: 'Phase 3 sur 5 - Tests Bêta et Optimisation',
      phaseDescription: 'Actuellement en phase de tests bêta où nous collectons les commentaires des utilisateurs, optimisons les performances et corrigeons les bugs critiques. Le modèle IA principal est fonctionnel, et nous nous concentrons maintenant sur l\'amélioration de la précision et de l\'expérience utilisateur.',
      phaseResearchPlanning: 'Phase 1: Recherche et Planification',
      phaseCoreDevlopment: 'Phase 2: Développement Principal',
      phaseBetaTesting: 'Phase 3: Tests Bêta',
      phaseProductionRelease: 'Phase 4: Sortie en Production',
      phaseFeatureEnhancement: 'Phase 5: Amélioration des Fonctionnalités',

      // Profile Page
      welcomeHey: 'Salut,',
      welcomeTitle: 'Bienvenue',
      welcomeTo: 'dans mon portfolio',
      welcomeName: 'Je suis Sahil Shrivastav',
      profileSubtitle: 'Ingénieur Logiciel | Analyste de Données | Développeur',
      profileDescription: 'Je suis un ingénieur logiciel passionné et analyste de données avec un vif intérêt pour l\'apprentissage de nouvelles technologies. Toujours en train de travailler sur des projets passionnants et d\'explorer des solutions innovantes.',
      aboutMe: 'À Propos de Moi',
      aboutMeText: 'Je suis un ingénieur logiciel passionné et analyste de données avec un vif intérêt pour l\'apprentissage de nouvelles technologies. Je travaille toujours sur des projets passionnants et j\'explore des solutions innovantes à des problèmes complexes.',
      downloadCV: 'Télécharger CV',
      technicalSkills: 'Compétences Techniques',
      myMindset: 'Mon État d\'Esprit',
      alwaysLearning: 'Toujours Apprendre',
      alwaysLearningText: 'Désireux d\'apprendre de nouvelles choses et de rester à jour avec les dernières technologies',
      innovationFocused: 'Axé sur l\'Innovation',
      innovationFocusedText: 'Toujours dans les nouvelles technologies et explorant des solutions de pointe',
      projectDriven: 'Orienté Projet',
      projectDrivenText: 'Toujours en train de travailler sur de nouvelles choses et des projets passionnants',
      myProjects: 'Mes Projets',
      myProjectsText: 'Explorez ma collection de projets et d\'applications innovants',
      viewProjects: 'Voir les Projets',
      currentMysteryProject: 'Projet Mystère Actuel',
      currentMysteryProjectText: 'Découvrez mon projet en cours et contribuez à son développement',
      learnMore: 'En Savoir Plus',
      getInTouch: 'Entrer en Contact',
      getInTouchText: 'Vous avez une question ou souhaitez collaborer? Connectons-nous!',
      contactMe: 'Contactez-moi',
      
      // Contact Page
      contactTitle: 'Entrer en Contact',
      contactSubtitle: 'Vous avez une question, souhaitez collaborer ou simplement dire bonjour ? J\'aimerais avoir de vos nouvelles !',
      emailMe: 'Envoyez-moi un Email',
      emailMeDesc: 'Je vous répondrai dans les 24 heures',
      sendEmail: 'Envoyer un Email',
      letsDiscuss: 'Discutons',
      letsDiscussDesc: 'Ouvert aux nouvelles opportunités et collaborations',
      availableFor: 'Disponible Pour',
      availableForDesc: 'Projets freelance, postes à temps plein et conseil',
      fullName: 'Nom Complet',
      fullNamePlaceholder: 'Votre nom complet',
      emailAddress: 'Adresse Email',
      emailPlaceholder: 'votre.email@exemple.com',
      subject: 'Sujet',
      subjectPlaceholder: 'De quoi s\'agit-il ?',
      messageLabel: 'Message',
      messagePlaceholder: 'Parlez-moi de votre projet, question ou dites simplement bonjour...',
      sendMessage: 'Envoyer le Message',
      sending: 'Envoi en cours...',
      messageSentSuccess: 'Merci ! Votre message a été envoyé avec succès.',

      // Settings
      settingsTitle: 'Paramètres',
      settingsSubtitle: 'Personnalisez votre expérience de portfolio',
      themeSettings: 'Paramètres de Thème',
      autoChange: 'Changement Automatique',
      autoChangeDesc: 'Changer automatiquement entre les thèmes de couleur',
      blueTheme: 'Thème Bleu',
      blueThemeDesc: 'Un schéma de couleurs bleu frais et professionnel',
      redTheme: 'Thème Rouge',
      redThemeDesc: 'Un schéma de couleurs rouge vibrant et énergique',
      greyTheme: 'Thème Gris',
      greyThemeDesc: 'Un schéma de couleurs gris minimal et élégant',
      languageSettings: 'Paramètres de Langue',
      selectLanguage: 'Sélectionner la Langue',
      bugReport: 'Signaler un Bug',
      bugReportDesc: 'Aidez-nous à améliorer en signalant les problèmes',
      bugScreenshot: 'Capture d\'Écran du Bug',
      bugDetails: 'Détails du Bug',
      bugDetailsPlaceholder: 'Décrivez le bug que vous avez rencontré...',
      submitBugReport: 'Soumettre le Rapport de Bug',
      bugReportSuccess: 'Rapport de bug soumis avec succès!',

      // Common
      save: 'Enregistrer',
      cancel: 'Annuler',
      submit: 'Soumettre',
      close: 'Fermer'
    },
    hi: {
      // Navigation
      profile: 'प्रोफ़ाइल',
      projects: 'प्रोजेक्ट्स',
      mysteryProject: 'रहस्यमय प्रोजेक्ट',
      contact: 'संपर्क',
      settings: 'सेटिंग्स',

      // Projects Page
      projectsTitle: 'मेरे प्रोजेक्ट्स',
      projectsSubtitle: 'मेरी तकनीकी विशेषज्ञता और रचनात्मकता का प्रदर्शन',
      liveDemo: 'लाइव डेमो',
      repository: 'रिपॉजिटरी',
      ecommerceTitle: 'ई-कॉमर्स प्लेटफॉर्म',
      ecommerceDesc: 'React और Node.js के साथ बनाया गया एक पूर्ण-स्टैक ई-कॉमर्स समाधान, जिसमें उपयोगकर्ता प्रमाणीकरण, भुगतान एकीकरण और एडमिन डैशबोर्ड है।',
      ecommerceSuggestion: 'बहुत अच्छा प्रोजेक्ट! ऑर्डर अपडेट के लिए रियल-टाइम नोटिफिकेशन जोड़ने पर विचार करें।',
      analyticsTitle: 'डेटा एनालिटिक्स डैशबोर्ड',
      analyticsDesc: 'Python और React का उपयोग करके डेटा विज़ुअलाइज़ेशन और एनालिटिक्स के लिए इंटरैक्टिव डैशबोर्ड, रियल-टाइम डेटा प्रोसेसिंग क्षमताओं के साथ।',
      analyticsSuggestion: 'प्रभावशाली विज़ुअलाइज़ेशन! एक्सपोर्ट फंक्शनैलिटी जोड़ना मूल्यवान होगा।',
      taskTitle: 'टास्क मैनेजमेंट ऐप',
      taskDesc: 'रियल-टाइम अपडेट, टीम सहयोग सुविधाओं और प्रगति ट्रैकिंग के साथ एक सहयोगी कार्य प्रबंधन एप्लिकेशन।',
      taskSuggestion: 'रियल-टाइम फीचर्स पसंद आए! मोबाइल ऐप वर्जन अमेजिंग होगा।',
      weatherTitle: 'मौसम पूर्वानुमान ऐप',
      weatherDesc: 'स्थान-आधारित पूर्वानुमान, इंटरैक्टिव मैप्स और कई APIs का उपयोग करके मौसम अलर्ट के साथ आधुनिक मौसम एप्लिकेशन।',
      weatherSuggestion: 'सुंदर UI! मौसम इतिहास चार्ट जोड़ना एक अच्छा स्पर्श होगा।',
      mlTitle: 'मशीन लर्निंग मॉडल',
      mlDesc: 'वेब इंटरफेस के साथ Python और scikit-learn का उपयोग करके ग्राहक व्यवहार विश्लेषण के लिए भविष्यसूचक एनालिटिक्स मॉडल।',
      mlSuggestion: 'उत्कृष्ट मॉडल सटीकता! मॉडल व्याख्या सुविधाएं जोड़ने पर विचार करें।',
      socialTitle: 'सोशल मीडिया क्लोन',
      socialDesc: 'पोस्ट, टिप्पणियां, लाइक्स, रियल-टाइम मैसेजिंग और उपयोगकर्ता प्रोफाइल के साथ पूर्ण-विशेषताओं वाला सोशल मीडिया प्लेटफॉर्म।',
      socialSuggestion: 'बेहतरीन सोशल फीचर्स! स्टोरी फंक्शनैलिटी जोड़ना ट्रेंडी होगा।',

      // Current Project Page
      mysteryProjectTitle: 'रहस्यमय प्रोजेक्ट: AI-संचालित कोड असिस्टेंट',
      mysteryProjectSubtitle: 'एक बुद्धिमान कोडिंग साथी जो संदर्भ समझता है और स्मार्ट सुझाव प्रदान करता है',
      projectAim: 'प्रोजेक्ट का उद्देश्य',
      projectAimDescription: 'एक AI-संचालित कोड असिस्टेंट विकसित करना जो कोड संदर्भ समझ सके, बुद्धिमान सुझाव प्रदान कर सके, संभावित बग्स का पता लगा सके, और डेवलपर्स को बेहतर कोड तेज़ी से लिखने में मदद कर सके। यह सिस्टम लोकप्रिय IDEs के साथ एकीकृत होगा और कई प्रोग्रामिंग भाषाओं का समर्थन करेगा।',
      realtimeAnalysis: 'रियल-टाइम कोड विश्लेषण और सुझाव',
      contextAwareCompletion: 'संदर्भ-जागरूक ऑटो-कम्प्लीशन',
      bugDetection: 'बग का पता लगाना और रोकथाम',
      codeOptimization: 'कोड ऑप्टिमाइजेशन सुझाव',
      multiLanguageSupport: 'बहु-भाषा समर्थन (Python, JavaScript, Java, आदि)',
      wantToContribute: 'योगदान देना चाहते हैं?',
      contributeDescription: 'यह प्रोजेक्ट इस दृष्टि को साकार करने में मदद के लिए जुनूनी डेवलपर्स, AI उत्साही और बीटा टेस्टर्स की तलाश में है। चाहे आप मशीन लर्निंग, IDE डेवलपमेंट, या यूजर एक्सपीरियंस डिज़ाइन में रुचि रखते हों, आपके लिए एक जगह है!',
      joinProject: 'प्रोजेक्ट में शामिल हों',
      joinMysteryProject: 'रहस्यमय प्रोजेक्ट में शामिल हों',
      fullName: 'पूरा नाम',
      emailAddress: 'ईमेल पता',
      yourSkills: 'आपके कौशल',
      skillsPlaceholder: 'जैसे, Python, Machine Learning, React',
      whyInterested: 'आप क्यों रुचि रखते हैं?',
      sendApplication: 'आवेदन भेजें',
      thankYouMessage: 'आपकी रुचि के लिए धन्यवाद! मैं जल्द ही आपसे संपर्क करूंगा।',
      
      // Current Issues and Limitations
      currentDrawbacks: 'वर्तमान कमियां',
      highComputationalReq: 'रियल-टाइम प्रोसेसिंग के लिए उच्च कम्प्यूटेशनल आवश्यकताएं',
      accuracyVaries: 'विभिन्न प्रोग्रामिंग भाषाओं में सटीकता काफी भिन्न होती है',
      contextLimited: 'संदर्भ समझ वर्तमान फ़ाइल के दायरे तक सीमित',
      integrationChallenges: 'विभिन्न IDE प्लेटफॉर्म के साथ एकीकरण चुनौतियां',
      
      technicalLimitations: 'तकनीकी सीमाएं',
      modelSizeConstraints: 'स्थानीय तैनाती के लिए मॉडल आकार की बाधाएं',
      limitedTrainingData: 'विशिष्ट प्रोग्रामिंग डोमेन के लिए सीमित प्रशिक्षण डेटा',
      complexArchitecture: 'जटिल प्रोजेक्ट आर्किटेक्चर को समझने में कठिनाई',
      performanceBottlenecks: 'बड़े कोडबेस के साथ प्रदर्शन अड़चनें',
      crossPlatformIssues: 'क्रॉस-प्लेटफॉर्म संगतता समस्याएं',
      
      currentIssues: 'वर्तमान समस्याएं',
      memoryLeaks: 'बैकग्राउंड प्रोसेसिंग सेवा में मेमोरी लीक',
      inconsistentSuggestions: 'एज केसेस के लिए असंगत सुझाव गुणवत्ता',
      extensionCrashes: 'कुछ फ़ाइल प्रकारों के साथ IDE एक्सटेंशन क्रैश',
      slowResponseTimes: 'जटिल कोड विश्लेषण के लिए धीमे प्रतिक्रिया समय',
      authenticationIssues: 'क्लाउड-आधारित सुविधाओं के साथ प्रमाणीकरण समस्याएं',
      
      developmentPhase: 'विकास चरण',
      phaseText: 'चरण 3 का 5 - बीटा परीक्षण और अनुकूलन',
      phaseDescription: 'वर्तमान में बीटा परीक्षण चरण में हैं जहां हम उपयोगकर्ता फीडबैक एकत्र कर रहे हैं, प्रदर्शन का अनुकूलन कर रहे हैं, और महत्वपूर्ण बग्स को ठीक कर रहे हैं। मुख्य AI मॉडल कार्यात्मक है, और अब हम सटीकता और उपयोगकर्ता अनुभव में सुधार पर ध्यान केंद्रित कर रहे हैं।',
      phaseResearchPlanning: 'चरण 1: अनुसंधान और योजना',
      phaseCoreDevlopment: 'चरण 2: मुख्य विकास',
      phaseBetaTesting: 'चरण 3: बीटा परीक्षण',
      phaseProductionRelease: 'चरण 4: उत्पादन रिलीज़',
      phaseFeatureEnhancement: 'चरण 5: सुविधा संवर्धन',

      // Profile Page
      welcomeHey: 'नमस्ते,',
      welcomeTitle: 'स्वागत है',
      welcomeTo: 'मेरे पोर्टफोलियो में',
      welcomeName: 'मैं साहिल श्रीवास्तव हूं',
      profileSubtitle: 'सॉफ्टवेयर इंजीनियर | डेटा एनालिस्ट | डेवलपर',
      profileDescription: 'मैं एक जुनूनी सॉफ्टवेयर इंजीनियर और डेटा एनालिस्ट हूं जिसकी नई तकनीकों को सीखने में गहरी रुचि है। हमेशा रोमांचक प्रोजेक्ट्स पर काम करता रहता हूं और नवाचार समाधान खोजता रहता हूं।',
      aboutMe: 'मेरे बारे में',
      aboutMeText: 'मैं एक जुनूनी सॉफ्टवेयर इंजीनियर और डेटा एनालिस्ट हूं जिसकी नई तकनीकों को सीखने में गहरी रुचि है। मैं हमेशा रोमांचक प्रोजेक्ट्स पर काम करता रहता हूं और जटिल समस्याओं के नवाचार समाधान खोजता रहता हूं।',
      downloadCV: 'CV डाउनलोड करें',
      technicalSkills: 'तकनीकी कौशल',
      myMindset: 'मेरी सोच',
      alwaysLearning: 'हमेशा सीखना',
      alwaysLearningText: 'नई चीजें सीखने और नवीनतम तकनीकों के साथ अपडेट रहने की इच्छा',
      innovationFocused: 'नवाचार केंद्रित',
      innovationFocusedText: 'हमेशा नई तकनीक में और अत्याधुनिक समाधानों की खोज',
      projectDriven: 'प्रोजेक्ट संचालित',
      projectDrivenText: 'हमेशा नई चीजों और रोमांचक प्रोजेक्ट्स पर काम करना',
      myProjects: 'मेरे प्रोजेक्ट्स',
      myProjectsText: 'नवाचार प्रोजेक्ट्स और एप्लिकेशन के मेरे संग्रह को देखें',
      viewProjects: 'प्रोजेक्ट्स देखें',
      currentMysteryProject: 'वर्तमान रहस्यमय प्रोजेक्ट',
      currentMysteryProjectText: 'मेरे चल रहे प्रोजेक्ट को खोजें और इसके विकास में योगदान दें',
      learnMore: 'और जानें',
      getInTouch: 'संपर्क करें',
      getInTouchText: 'कोई सवाल है या सहयोग करना चाहते हैं? आइए जुड़ें!',
      contactMe: 'मुझसे संपर्क करें',
      
      // Contact Page
      contactTitle: 'संपर्क में रहें',
      contactSubtitle: 'कोई प्रश्न, सहयोग की इच्छा, या सिर्फ नमस्कार करना चाहते हैं? मुझे आपसे सुनना अच्छा लगेगा!',
      emailMe: 'मुझे ईमेल करें',
      emailMeDesc: 'मैं 24 घंटों में आपको जवाब दूंगा',
      sendEmail: 'ईमेल भेजें',
      letsDiscuss: 'चर्चा करते हैं',
      letsDiscussDesc: 'नए अवसरों और सहयोग के लिए खुला',
      availableFor: 'उपलब्ध',
      availableForDesc: 'फ्रीलांस प्रोजेक्ट, पूर्णकालिक नौकरियां और सलाहकारी',
      fullName: 'पूरा नाम',
      fullNamePlaceholder: 'आपका पूरा नाम',
      emailAddress: 'ईमेल पता',
      emailPlaceholder: 'आपका.ईमेल@उदाहरण.कॉम',
      subject: 'विषय',
      subjectPlaceholder: 'यह किस बारे में है?',
      messageLabel: 'संदेश',
      messagePlaceholder: 'मुझे अपने प्रोजेक्ट, प्रश्न के बारे में बताएं या सिर्फ नमस्कार करें...',
      sendMessage: 'संदेश भेजें',
      sending: 'भेजा जा रहा है...',
      messageSentSuccess: 'धन्यवाद! आपका संदेश सफलतापूर्वक भेज दिया गया है।',

      // Settings
      settingsTitle: 'सेटिंग्स',
      settingsSubtitle: 'अपने पोर्टफोलियो अनुभव को कस्टमाइज़ करें',
      themeSettings: 'थीम सेटिंग्स',
      autoChange: 'ऑटो चेंज',
      autoChangeDesc: 'रंग थीम के बीच स्वचालित रूप से बदलें',
      blueTheme: 'नीली थीम',
      blueThemeDesc: 'एक शीतल और पेशेवर नीला रंग योजना',
      redTheme: 'लाल थीम',
      redThemeDesc: 'एक जीवंत और ऊर्जावान लाल रंग योजना',
      greyTheme: 'स्लेटी थीम',
      greyThemeDesc: 'एक न्यूनतम और सुरुचिपूर्ण धूसर रंग योजना',
      languageSettings: 'भाषा सेटिंग्स',
      selectLanguage: 'भाषा चुनें',
      bugReport: 'बग रिपोर्ट करें',
      bugReportDesc: 'समस्याओं की रिपोर्ट करके हमें बेहतर बनाने में मदद करें',
      bugScreenshot: 'बग स्क्रीनशॉट',
      bugDetails: 'बग विवरण',
      bugDetailsPlaceholder: 'आपको जो बग मिला उसका वर्णन करें...',
      submitBugReport: 'बग रिपोर्ट सबमिट करें',
      bugReportSuccess: 'बग रिपोर्ट सफलतापूर्वक सबमिट की गई!',

      // Common
      save: 'सहेजें',
      cancel: 'रद्द करें',
      submit: 'सबमिट करें',
      close: 'बंद करें'
    },
    zh: {
      // Navigation
      profile: '个人资料',
      projects: '项目',
      mysteryProject: '神秘项目',
      contact: '联系',
      settings: '设置',

      // Projects Page
      projectsTitle: '我的项目',
      projectsSubtitle: '展示我的技术专长和创造力',
      liveDemo: '在线演示',
      repository: '代码仓库',
      ecommerceTitle: '电商平台',
      ecommerceDesc: '使用React和Node.js构建的全栈电商解决方案，包含用户认证、支付集成和管理仪表板。',
      ecommerceSuggestion: '很棒的项目！考虑添加订单更新的实时通知功能。',
      analyticsTitle: '数据分析仪表板',
      analyticsDesc: '使用Python和React构建的交互式数据可视化和分析仪表板，具有实时数据处理能力。',
      analyticsSuggestion: '令人印象深刻的可视化！添加导出功能会很有价值。',
      taskTitle: '任务管理应用',
      taskDesc: '具有实时更新、团队协作功能和进度跟踪的协作任务管理应用程序。',
      taskSuggestion: '喜欢实时功能！移动应用版本会很棒。',
      weatherTitle: '天气预报应用',
      weatherDesc: '现代天气应用，具有基于位置的预报、交互式地图和使用多个API的天气警报。',
      weatherSuggestion: '美丽的UI！添加天气历史图表会是个不错的功能。',
      mlTitle: '机器学习模型',
      mlDesc: '使用Python和scikit-learn进行客户行为分析的预测分析模型，带有Web界面。',
      mlSuggestion: '出色的模型准确性！考虑添加模型解释功能。',
      socialTitle: '社交媒体克隆',
      socialDesc: '功能完整的社交媒体平台，包含帖子、评论、点赞、实时消息和用户档案。',
      socialSuggestion: '很棒的社交功能！添加故事功能会很时尚。',

      // Current Project Page
      mysteryProjectTitle: '神秘项目：AI驱动的代码助手',
      mysteryProjectSubtitle: '一个理解上下文并提供智能建议的智能编程伙伴',
      projectAim: '项目目标',
      projectAimDescription: '开发一个AI驱动的代码助手，能够理解代码上下文，提供智能建议，检测潜在错误，并帮助开发者更快地编写更好的代码。该系统将与流行的IDE集成，并支持多种编程语言。',
      realtimeAnalysis: '实时代码分析和建议',
      contextAwareCompletion: '上下文感知自动完成',
      bugDetection: '错误检测和预防',
      codeOptimization: '代码优化建议',
      multiLanguageSupport: '多语言支持（Python、JavaScript、Java等）',
      wantToContribute: '想要贡献？',
      contributeDescription: '这个项目正在寻找充满激情的开发者、AI爱好者和测试人员来帮助实现这个愿景。无论您对机器学习、IDE开发还是用户体验设计感兴趣，都有您的位置！',
      joinProject: '加入项目',
      joinMysteryProject: '加入神秘项目',
      fullName: '全名',
      emailAddress: '邮箱地址',
      yourSkills: '您的技能',
      skillsPlaceholder: '例如，Python、机器学习、React',
      whyInterested: '您为什么感兴趣？',
      sendApplication: '发送申请',
      thankYouMessage: '感谢您的兴趣！我会尽快与您联系。',
      
      // Current Issues and Limitations
      currentDrawbacks: '当前缺点',
      highComputationalReq: '实时处理的高计算要求',
      accuracyVaries: '不同编程语言的准确性差异很大',
      contextLimited: '上下文理解仅限于当前文件范围',
      integrationChallenges: '与各种IDE平台的集成挑战',
      
      technicalLimitations: '技术限制',
      modelSizeConstraints: '本地部署的模型大小限制',
      limitedTrainingData: '小众编程领域的有限训练数据',
      complexArchitecture: '理解复杂项目架构的困难',
      performanceBottlenecks: '大型代码库的性能瓶颈',
      crossPlatformIssues: '跨平台兼容性问题',
      
      currentIssues: '当前问题',
      memoryLeaks: '后台处理服务中的内存泄漏',
      inconsistentSuggestions: '边缘情况的建议质量不一致',
      extensionCrashes: 'IDE扩展在某些文件类型下崩溃',
      slowResponseTimes: '复杂代码分析的响应时间慢',
      authenticationIssues: '基于云的功能的身份验证问题',
      
      developmentPhase: '开发阶段',
      phaseText: '第3阶段，共5阶段 - Beta测试与优化',
      phaseDescription: '目前在Beta测试阶段，我们正在收集用户反馈，优化性能，并修复关键错误。核心AI模型是功能性的，现在我们专注于提高准确性和用户体验。',
      phaseResearchPlanning: '第1阶段：研究与规划',
      phaseCoreDevlopment: '第2阶段：核心开发',
      phaseBetaTesting: '第3阶段：Beta测试',
      phaseProductionRelease: '第4阶段：生产发布',
      phaseFeatureEnhancement: '第5阶段：功能增强',

      // Profile Page
      welcomeHey: '嗨，',
      welcomeTitle: '欢迎',
      welcomeTo: '来到我的作品集',
      welcomeName: '我是Sahil Shrivastav',
      profileSubtitle: '软件工程师 | 数据分析师 | 开发者',
      profileDescription: '我是一名充满激情的软件工程师和数据分析师，对学习新技术有着浓厚的兴趣。总是在进行令人兴奋的项目，并探索创新解决方案。',
      aboutMe: '关于我',
      aboutMeText: '我是一名充满激情的软件工程师和数据分析师，对学习新技术有着浓厚的兴趣。我总是在进行令人兴奋的项目，并探索复杂问题的创新解决方案。',
      downloadCV: '下载简历',
      technicalSkills: '技术技能',
      myMindset: '我的心态',
      alwaysLearning: '持续学习',
      alwaysLearningText: '热衷于学习新事物并跟上最新技术',
      innovationFocused: '创新专注',
      innovationFocusedText: '始终关注新技术并探索尖端解决方案',
      projectDriven: '项目驱动',
      projectDrivenText: '始终在进行新事物和令人兴奋的项目',
      myProjects: '我的项目',
      myProjectsText: '探索我的创新项目和应用程序集合',
      viewProjects: '查看项目',
      currentMysteryProject: '当前神秘项目',
      currentMysteryProjectText: '发现我正在进行的项目并为其发展做出贡献',
      learnMore: '了解更多',
      getInTouch: '联系',
      getInTouchText: '有问题或想合作？让我们联系！',
      contactMe: '联系我',
      
      // Contact Page
      contactTitle: '联系我',
      contactSubtitle: '有问题、想合作或只是打个招呼？我很乐意听到您的声音！',
      emailMe: '发邮件给我',
      emailMeDesc: '我会在24小时内回复您',
      sendEmail: '发送邮件',
      letsDiscuss: '让我们讨论',
      letsDiscussDesc: '对新机会和合作持开放态度',
      availableFor: '可用于',
      availableForDesc: '自由职业项目、全职工作和咨询',
      fullName: '全名',
      fullNamePlaceholder: '您的全名',
      emailAddress: '邮箱地址',
      emailPlaceholder: '您的邮箱@示例.com',
      subject: '主题',
      subjectPlaceholder: '这是关于什么？',
      messageLabel: '消息',
      messagePlaceholder: '告诉我关于您的项目、问题或只是打个招呼...',
      sendMessage: '发送消息',
      sending: '发送中...',
      messageSentSuccess: '谢谢！您的消息已成功发送。',

      // Settings
      settingsTitle: '设置',
      settingsSubtitle: '自定义您的作品集体验',
      themeSettings: '主题设置',
      autoChange: '自动更换',
      autoChangeDesc: '自动在颜色主题之间循环',
      blueTheme: '蓝色主题',
      blueThemeDesc: '清爽专业的蓝色配色方案',
      redTheme: '红色主题',
      redThemeDesc: '充满活力的红色配色方案',
      greyTheme: '灰色主题',
      greyThemeDesc: '简约优雅的灰色配色方案',
      languageSettings: '语言设置',
      selectLanguage: '选择语言',
      bugReport: '报告错误',
      bugReportDesc: '通过报告问题帮助我们改进',
      bugScreenshot: '错误截图',
      bugDetails: '错误详情',
      bugDetailsPlaceholder: '描述您遇到的错误...',
      submitBugReport: '提交错误报告',
      bugReportSuccess: '错误报告提交成功！',

      // Common
      save: '保存',
      cancel: '取消',
      submit: '提交',
      close: '关闭'
    },
    it: {
      // Navigation
      profile: 'Profilo',
      projects: 'Progetti',
      mysteryProject: 'Progetto Misterioso',
      contact: 'Contatto',
      settings: 'Impostazioni',

      // Projects Page
      projectsTitle: 'I Miei Progetti',
      projectsSubtitle: 'Una vetrina della mia competenza tecnica e creatività',
      liveDemo: 'Demo Live',
      repository: 'Repository',
      ecommerceTitle: 'Piattaforma E-Commerce',
      ecommerceDesc: 'Una soluzione e-commerce full-stack costruita con React e Node.js, con autenticazione utente, integrazione pagamenti e dashboard admin.',
      ecommerceSuggestion: 'Ottimo progetto! Considera di aggiungere notifiche in tempo reale per gli aggiornamenti ordini.',
      analyticsTitle: 'Dashboard Analisi Dati',
      analyticsDesc: 'Dashboard interattiva per visualizzazione e analisi dati usando Python e React, con capacità di elaborazione dati in tempo reale.',
      analyticsSuggestion: 'Visualizzazione impressionante! Aggiungere funzionalità di esportazione sarebbe prezioso.',
      taskTitle: 'App Gestione Attività',
      taskDesc: 'Un\'applicazione collaborativa di gestione attività con aggiornamenti in tempo reale, funzionalità di collaborazione team e monitoraggio progressi.',
      taskSuggestion: 'Adoro le funzionalità in tempo reale! Una versione app mobile sarebbe fantastica.',
      weatherTitle: 'App Previsioni Meteo',
      weatherDesc: 'Applicazione meteo moderna con previsioni basate sulla posizione, mappe interattive e avvisi meteo usando multiple API.',
      weatherSuggestion: 'Bellissima UI! Aggiungere grafici cronologia meteo sarebbe un bel tocco.',
      mlTitle: 'Modello Machine Learning',
      mlDesc: 'Modello analitica predittiva per analisi comportamento clienti usando Python e scikit-learn con interfaccia web.',
      mlSuggestion: 'Eccellente accuratezza modello! Considera di aggiungere funzionalità spiegazione modello.',
      socialTitle: 'Clone Social Media',
      socialDesc: 'Piattaforma social media completa con post, commenti, like, messaggistica in tempo reale e profili utente.',
      socialSuggestion: 'Ottime funzionalità social! Aggiungere funzionalità storie sarebbe alla moda.',

      // Current Project Page
      mysteryProjectTitle: 'Progetto Misterioso: Assistente Codice AI',
      mysteryProjectSubtitle: 'Un compagno di programmazione intelligente che comprende il contesto e fornisce suggerimenti intelligenti',
      projectAim: 'Obiettivo del Progetto',
      projectAimDescription: 'Sviluppare un assistente di codice alimentato da AI che possa comprendere il contesto del codice, fornire suggerimenti intelligenti, rilevare bug potenziali e aiutare gli sviluppatori a scrivere codice migliore più velocemente. Il sistema si integrerà con IDE popolari e supporterà più linguaggi di programmazione.',
      realtimeAnalysis: 'Analisi codice in tempo reale e suggerimenti',
      contextAwareCompletion: 'Auto-completamento consapevole del contesto',
      bugDetection: 'Rilevamento e prevenzione bug',
      codeOptimization: 'Raccomandazioni ottimizzazione codice',
      multiLanguageSupport: 'Supporto multi-linguaggio (Python, JavaScript, Java, ecc.)',
      wantToContribute: 'Vuoi Contribuire?',
      contributeDescription: 'Questo progetto sta cercando sviluppatori appassionati, entusiasti AI e beta tester per aiutare a rendere reale questa visione. Che tu sia interessato al machine learning, sviluppo IDE o design esperienza utente, c\'è un posto per te!',
      joinProject: 'Unisciti al Progetto',
      joinMysteryProject: 'Unisciti al Progetto Misterioso',
      fullName: 'Nome Completo',
      emailAddress: 'Indirizzo Email',
      yourSkills: 'Le Tue Competenze',
      skillsPlaceholder: 'es., Python, Machine Learning, React',
      whyInterested: 'Perché sei interessato?',
      sendApplication: 'Invia Candidatura',
      thankYouMessage: 'Grazie per il tuo interesse! Ti ricontatterò presto.',
      
      // Current Issues and Limitations
      currentDrawbacks: 'Svantaggi Attuali',
      highComputationalReq: 'Alti requisiti computazionali per l\'elaborazione in tempo reale',
      accuracyVaries: 'L\'accuratezza varia significativamente tra diversi linguaggi di programmazione',
      contextLimited: 'Comprensione del contesto limitata all\'ambito del file corrente',
      integrationChallenges: 'Sfide di integrazione con varie piattaforme IDE',
      
      technicalLimitations: 'Limitazioni Tecniche',
      modelSizeConstraints: 'Vincoli di dimensione del modello per il deployment locale',
      limitedTrainingData: 'Dati di addestramento limitati per domini di programmazione di nicchia',
      complexArchitecture: 'Difficoltà nel comprendere architetture di progetto complesse',
      performanceBottlenecks: 'Colli di bottiglia delle prestazioni con grandi basi di codice',
      crossPlatformIssues: 'Problemi di compatibilità cross-platform',
      
      currentIssues: 'Problemi Attuali',
      memoryLeaks: 'Perdite di memoria nel servizio di elaborazione in background',
      inconsistentSuggestions: 'Qualità dei suggerimenti inconsistente per i casi limite',
      extensionCrashes: 'Crash dell\'estensione IDE con certi tipi di file',
      slowResponseTimes: 'Tempi di risposta lenti per l\'analisi di codice complesso',
      authenticationIssues: 'Problemi di autenticazione con funzionalità basate su cloud',
      
      developmentPhase: 'Fase di Sviluppo',
      phaseText: 'Fase 3 di 5 - Test Beta e Ottimizzazione',
      phaseDescription: 'Attualmente nella fase di test beta dove stiamo raccogliendo feedback degli utenti, ottimizzando le prestazioni e correggendo bug critici. Il modello AI principale è funzionale, e ora ci stiamo concentrando sul miglioramento dell\'accuratezza e dell\'esperienza utente.',
      phaseResearchPlanning: 'Fase 1: Ricerca e Pianificazione',
      phaseCoreDevlopment: 'Fase 2: Sviluppo Principale',
      phaseBetaTesting: 'Fase 3: Test Beta',
      phaseProductionRelease: 'Fase 4: Rilascio in Produzione',
      phaseFeatureEnhancement: 'Fase 5: Miglioramento delle Funzionalità',

      // Profile Page
      welcomeHey: 'Ciao,',
      welcomeTitle: 'Benvenuto',
      welcomeTo: 'nel mio portfolio',
      welcomeName: 'Sono Sahil Shrivastav',
      profileSubtitle: 'Ingegnere Software | Analista Dati | Sviluppatore',
      profileDescription: 'Sono un ingegnere software appassionato e analista dati con un forte interesse nell\'apprendimento di nuove tecnologie. Sempre al lavoro su progetti entusiasmanti ed esplorando soluzioni innovative.',
      aboutMe: 'Chi Sono',
      aboutMeText: 'Sono un ingegnere software appassionato e analista dati con un forte interesse nell\'apprendimento di nuove tecnologie. Lavoro sempre su progetti entusiasmanti ed esploro soluzioni innovative a problemi complessi.',
      downloadCV: 'Scarica CV',
      technicalSkills: 'Competenze Tecniche',
      myMindset: 'La Mia Mentalità',
      alwaysLearning: 'Sempre Apprendimento',
      alwaysLearningText: 'Desideroso di imparare cose nuove e rimanere aggiornato con le ultime tecnologie',
      innovationFocused: 'Focalizzato sull\'Innovazione',
      innovationFocusedText: 'Sempre interessato alle nuove tecnologie ed esplorando soluzioni all\'avanguardia',
      projectDriven: 'Orientato ai Progetti',
      projectDrivenText: 'Sempre al lavoro su cose nuove e progetti entusiasmanti',
      myProjects: 'I Miei Progetti',
      myProjectsText: 'Esplora la mia collezione di progetti e applicazioni innovative',
      viewProjects: 'Visualizza Progetti',
      currentMysteryProject: 'Progetto Misterioso Attuale',
      currentMysteryProjectText: 'Scopri il mio progetto in corso e contribuisci al suo sviluppo',
      learnMore: 'Scopri di Più',
      getInTouch: 'Contattami',
      getInTouchText: 'Hai una domanda o vuoi collaborare? Mettiamoci in contatto!',
      contactMe: 'Contattami',
      
      // Contact Page
      contactTitle: 'Mettiti in Contatto',
      contactSubtitle: 'Hai una domanda, vuoi collaborare o semplicemente salutare? Mi piacerebbe sentirti!',
      emailMe: 'Inviami una Email',
      emailMeDesc: 'Ti risponderò entro 24 ore',
      sendEmail: 'Invia Email',
      letsDiscuss: 'Discutiamo',
      letsDiscussDesc: 'Aperto a nuove opportunità e collaborazioni',
      availableFor: 'Disponibile Per',
      availableForDesc: 'Progetti freelance, ruoli a tempo pieno e consulenza',
      fullName: 'Nome Completo',
      fullNamePlaceholder: 'Il tuo nome completo',
      emailAddress: 'Indirizzo Email',
      emailPlaceholder: 'tua.email@esempio.com',
      subject: 'Oggetto',
      subjectPlaceholder: 'Di cosa si tratta?',
      messageLabel: 'Messaggio',
      messagePlaceholder: 'Parlami del tuo progetto, domanda o semplicemente saluta...',
      sendMessage: 'Invia Messaggio',
      sending: 'Invio in corso...',
      messageSentSuccess: 'Grazie! Il tuo messaggio è stato inviato con successo.',

      // Settings
      settingsTitle: 'Impostazioni',
      settingsSubtitle: 'Personalizza la tua esperienza del portfolio',
      themeSettings: 'Impostazioni Tema',
      autoChange: 'Cambio Automatico',
      autoChangeDesc: 'Cambia automaticamente tra i temi di colore',
      blueTheme: 'Tema Blu',
      blueThemeDesc: 'Una combinazione di colori blu fresca e professionale',
      redTheme: 'Tema Rosso',
      redThemeDesc: 'Una combinazione di colori rosso vibrante ed energica',
      greyTheme: 'Tema Grigio',
      greyThemeDesc: 'Una combinazione di colori grigio minimale ed elegante',
      languageSettings: 'Impostazioni Lingua',
      selectLanguage: 'Seleziona Lingua',
      bugReport: 'Segnala Bug',
      bugReportDesc: 'Aiutaci a migliorare segnalando i problemi',
      bugScreenshot: 'Screenshot del Bug',
      bugDetails: 'Dettagli del Bug',
      bugDetailsPlaceholder: 'Descrivi il bug che hai riscontrato...',
      submitBugReport: 'Invia Segnalazione Bug',
      bugReportSuccess: 'Segnalazione bug inviata con successo!',

      // Common
      save: 'Salva',
      cancel: 'Annulla',
      submit: 'Invia',
      close: 'Chiudi'
    },
    ja: {
      // Navigation
      profile: 'プロフィール',
      projects: 'プロジェクト',
      mysteryProject: 'ミステリープロジェクト',
      contact: 'お問い合わせ',
      settings: '設定',

      // Projects Page
      projectsTitle: '私のプロジェクト',
      projectsSubtitle: '技術的専門知識と創造性のショーケース',
      liveDemo: 'ライブデモ',
      repository: 'リポジトリ',
      ecommerceTitle: 'Eコマースプラットフォーム',
      ecommerceDesc: 'ReactとNode.jsで構築されたフルスタックEコマースソリューション、ユーザー認証、決済統合、管理ダッシュボードを搭載。',
      ecommerceSuggestion: '素晴らしいプロジェクト！注文更新のリアルタイム通知の追加を検討してください。',
      analyticsTitle: 'データ分析ダッシュボード',
      analyticsDesc: 'PythonとReactを使用したデータ可視化と分析のためのインタラクティブダッシュボード、リアルタイムデータ処理機能付き。',
      analyticsSuggestion: '印象的な可視化！エクスポート機能の追加は価値があるでしょう。',
      taskTitle: 'タスク管理アプリ',
      taskDesc: 'リアルタイム更新、チーム協力機能、進捗追跡を備えた協力的タスク管理アプリケーション。',
      taskSuggestion: 'リアルタイム機能が素晴らしい！モバイルアプリ版があれば最高です。',
      weatherTitle: '天気予報アプリ',
      weatherDesc: '位置ベースの予報、インタラクティブマップ、複数APIを使用した天気警報を備えたモダン天気アプリケーション。',
      weatherSuggestion: '美しいUI！天気履歴チャートの追加は素敵なタッチでしょう。',
      mlTitle: '機械学習モデル',
      mlDesc: 'PythonとScikit-learnを使用した顧客行動分析のための予測分析モデル、Webインターフェース付き。',
      mlSuggestion: '優秀なモデル精度！モデル説明機能の追加を検討してください。',
      socialTitle: 'ソーシャルメディアクローン',
      socialDesc: '投稿、コメント、いいね、リアルタイムメッセージング、ユーザープロフィールを備えた本格的ソーシャルメディアプラットフォーム。',
      socialSuggestion: '素晴らしいソーシャル機能！ストーリー機能の追加がトレンディでしょう。',

      // Current Project Page
      mysteryProjectTitle: 'ミステリープロジェクト：AI駆動コードアシスタント',
      mysteryProjectSubtitle: 'コンテキストを理解し、スマートな提案を提供するインテリジェントなコーディングコンパニオン',
      projectAim: 'プロジェクトの目的',
      projectAimDescription: 'コードのコンテキストを理解し、インテリジェントな提案を提供し、潜在的なバグを検出し、開発者がより良いコードをより速く書けるようにするAI駆動のコードアシスタントを開発すること。システムは人気のIDEと統合され、複数のプログラミング言語をサポートします。',
      realtimeAnalysis: 'リアルタイムコード分析と提案',
      contextAwareCompletion: 'コンテキスト認識オートコンプリート',
      bugDetection: 'バグ検出と予防',
      codeOptimization: 'コード最適化の推奨事項',
      multiLanguageSupport: '多言語サポート（Python、JavaScript、Javaなど）',
      wantToContribute: '貢献したいですか？',
      contributeDescription: 'このプロジェクトは、この構想を実現するために情熱的な開発者、AI愛好家、ベータテスターを探しています。機械学習、IDE開発、またはユーザーエクスペリエンスデザインに興味があるかどうかに関わらず、あなたの場所があります！',
      joinProject: 'プロジェクトに参加',
      joinMysteryProject: 'ミステリープロジェクトに参加',
      fullName: '氏名',
      emailAddress: 'メールアドレス',
      yourSkills: 'あなたのスキル',
      skillsPlaceholder: '例：Python、機械学習、React',
      whyInterested: 'なぜ興味があるのですか？',
      sendApplication: '申込書を送信',
      thankYouMessage: 'ご興味をお持ちいただきありがとうございます！すぐにご連絡いたします。',
      
      // Current Issues and Limitations
      currentDrawbacks: '現在の欠点',
      highComputationalReq: 'リアルタイム処理のための高い計算要件',
      accuracyVaries: '異なるプログラミング言語間で精度が大幅に変動',
      contextLimited: 'コンテキスト理解が現在のファイル範囲に限定',
      integrationChallenges: '様々なIDEプラットフォームとの統合課題',
      
      technicalLimitations: '技術的制限',
      modelSizeConstraints: 'ローカル展開のためのモデルサイズ制約',
      limitedTrainingData: 'ニッチなプログラミングドメインの限定的な訓練データ',
      complexArchitecture: '複雑なプロジェクトアーキテクチャの理解困難',
      performanceBottlenecks: '大規模コードベースでのパフォーマンスボトルネック',
      crossPlatformIssues: 'クロスプラットフォーム互換性問題',
      
      currentIssues: '現在の問題',
      memoryLeaks: 'バックグラウンド処理サービスでのメモリリーク',
      inconsistentSuggestions: 'エッジケースでの一貫性のない提案品質',
      extensionCrashes: '特定のファイルタイプでのIDE拡張機能のクラッシュ',
      slowResponseTimes: '複雑なコード分析での応答時間の遅延',
      authenticationIssues: 'クラウドベース機能での認証問題',
      
      developmentPhase: '開発段階',
      phaseText: 'フェーズ3/5 - ベータテストと最適化',
      phaseDescription: '現在ベータテストフェーズにあり、ユーザーフィードバックの収集、パフォーマンスの最適化、重要なバグの修正を行っています。コアAIモデルは機能的で、現在は精度とユーザーエクスペリエンスの改善に焦点を当てています。',
      phaseResearchPlanning: 'フェーズ1：研究と計画',
      phaseCoreDevlopment: 'フェーズ2：コア開発',
      phaseBetaTesting: 'フェーズ3：ベータテスト',
      phaseProductionRelease: 'フェーズ4：本番リリース',
      phaseFeatureEnhancement: 'フェーズ5：機能強化',

      // Profile Page
      welcomeHey: 'こんにちは、',
      welcomeTitle: 'ようこそ',
      welcomeTo: '私のポートフォリオへ',
      welcomeName: '私はサヒル・シュリヴァスタヴです',
      profileSubtitle: 'ソフトウェアエンジニア | データアナリスト | 開発者',
      profileDescription: '新しい技術を学ぶことに強い関心を持つ情熱的なソフトウェアエンジニア兼データアナリストです。常にエキサイティングなプロジェクトに取り組み、革新的なソリューションを探求しています。',
      aboutMe: '自己紹介',
      aboutMeText: '新しい技術を学ぶことに強い関心を持つ情熱的なソフトウェアエンジニア兼データアナリストです。常にエキサイティングなプロジェクトに取り組み、複雑な問題に対する革新的なソリューションを探求しています。',
      downloadCV: 'CV をダウンロード',
      technicalSkills: '技術スキル',
      myMindset: '私のマインドセット',
      alwaysLearning: '常に学習',
      alwaysLearningText: '新しいことを学び、最新の技術について常に更新することに熱心',
      innovationFocused: 'イノベーション重視',
      innovationFocusedText: '常に新しい技術に興味を持ち、最先端のソリューションを探求',
      projectDriven: 'プロジェクト志向',
      projectDrivenText: '常に新しいことやエキサイティングなプロジェクトに取り組んでいます',
      myProjects: '私のプロジェクト',
      myProjectsText: '革新的なプロジェクトとアプリケーションのコレクションをご覧ください',
      viewProjects: 'プロジェクトを見る',
      currentMysteryProject: '現在のミステリープロジェクト',
      currentMysteryProjectText: '進行中のプロジェクトを発見し、その開発に貢献してください',
      learnMore: '詳細を見る',
      getInTouch: 'お問い合わせ',
      getInTouchText: '質問がありますか、それとも協力したいですか？ つながりましょう！',
      contactMe: 'お問い合わせ',
      
      // Contact Page
      contactTitle: 'お問い合わせ',
      contactSubtitle: 'ご質問、コラボレーション、またはご挨拶でもかまいません。お話をお聞かせいただければ幸いです！',
      emailMe: 'メールで連絡',
      emailMeDesc: '24時間以内に返信いたします',
      sendEmail: 'メール送信',
      letsDiscuss: 'ご相談しましょう',
      letsDiscussDesc: '新しい機会やコラボレーションを歓迎します',
      availableFor: '対応可能',
      availableForDesc: 'フリーランスプロジェクト、正社員、コンサルティング',
      fullName: 'お名前',
      fullNamePlaceholder: 'お名前を入力してください',
      emailAddress: 'メールアドレス',
      emailPlaceholder: 'あなたのメール@例.com',
      subject: '件名',
      subjectPlaceholder: 'どのようなご用件でしょうか？',
      messageLabel: 'メッセージ',
      messagePlaceholder: 'プロジェクトやご質問について教えてください。お気軽にどうぞ...',
      sendMessage: 'メッセージ送信',
      sending: '送信中...',
      messageSentSuccess: 'ありがとうございます！メッセージが正常に送信されました。',

      // Settings
      settingsTitle: '設定',
      settingsSubtitle: 'ポートフォリオ体験をカスタマイズ',
      themeSettings: 'テーマ設定',
      autoChange: '自動変更',
      autoChangeDesc: 'カラーテーマを自動的に循環',
      blueTheme: 'ブルーテーマ',
      blueThemeDesc: '爽やかでプロフェッショナルな青の配色',
      redTheme: 'レッドテーマ',
      redThemeDesc: '鮮やかでエネルギッシュな赤の配色',
      greyTheme: 'グレーテーマ',
      greyThemeDesc: 'ミニマルで洗練されたグレーの配色',
      languageSettings: '言語設定',
      selectLanguage: '言語を選択',
      bugReport: 'バグ報告',
      bugReportDesc: '問題を報告して改善にご協力ください',
      bugScreenshot: 'バグのスクリーンショット',
      bugDetails: 'バグの詳細',
      bugDetailsPlaceholder: '遭遇したバグについて説明してください...',
      submitBugReport: 'バグ報告を送信',
      bugReportSuccess: 'バグ報告が正常に送信されました!',

      // Common
      save: '保存',
      cancel: 'キャンセル',
      submit: '送信',
      close: '閉じる'
    }
  };

  const setLanguage = (languageCode) => {
    localStorage.setItem('selectedLanguage', languageCode);
    setCurrentLanguage(languageCode);
    // Force a re-render by dispatching a custom event
    window.dispatchEvent(new CustomEvent('languageChange', { detail: languageCode }));
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const getCurrentLanguage = () => {
    return languages.find(lang => lang.code === currentLanguage) || languages[0];
  };

  return {
    currentLanguage,
    setLanguage,
    languages,
    t,
    getCurrentLanguage
  };
};

export default useLanguage;